version: '3'
services:
  influxdb:
    image: influxdb:2.7-alpine
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=admin
    - DOCKER_INFLUXDB_INIT_PASSWORD=admin_password
    - DOCKER_INFLUXDB_INIT_ORG=metrics
    - DOCKER_INFLUXDB_INIT_BUCKET=octograph
    - DOCKER_INFLUXDB_INIT_RETENTION=104w
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secret_admin_token
    ports:
      - "18086:8086"
  grafana:
    image: grafana/grafana-oss:10.2.3
    ports:
      - "13000:3000"
    depends_on:
      - influxdb
    volumes:
    - ./grafana/provisioning:/etc/grafana/provisioning
    - ./grafana/lib/dashboards:/var/lib/grafana/dashboards
