apiVersion: 1

deleteDatasources:
- name: InfluxDB
  orgId: 1

datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  jsonData:
    dbName: octopus
    httpMode: GET
    httpHeaderName1: 'Authorization'
  secureJsonData:
    httpHeaderValue1: 'Token secret_admin_token'
